service: joke-bot
variablesResolutionMode: 20210326
useDotenv: true
provider:
  name: aws
  stage: ${opt:stage, 'local'}
  environment:
    ENV: ${opt:stage, 'local'}
    SLACK_TOKEN: ${env:SLACK_BOT_TOKEN, ssm:/SLACK_BOT_TOKEN}
    github_token: ${env:github_token, ssm:/GITHUB_TOKEN}
  runtime: nodejs12.x
  versionFunctions: false
  region: us-east-2
  iam:
    role:
      name: ${opt:stage, 'local'}-build-bot-role
      statements:
      - Effect: 'Allow'
        Action: 'lambda:InvokeFunction'
        Resource: arn:aws:lambda:${aws:region}:${aws:accountId}:function:build-bot-prod-build-status-worker

functions:
  get-joke:
    handler: lambda.getJoke
    timeout: 10
    memorySize: 128
    events:
      - http:
          path: /fg64rvaFaSs91m5ND7wYWlhyt5c62/joke
          method: post
          cors:
            origin: '*'


